### PR TITLE
fix:Form validation should occur when a submit action is triggered,resolved #310

### LINKED ISSUE #310: Form validation should occur when a submit action is triggered
表单验证应在触发提交操作时，现在新建后，再次打开新建弹窗，直接触发表单验证
image

### PR DESCRIPTION
**Pull request by MapleWithoutWords**
修改之后，关闭编辑弹窗，打开新增弹窗，不会触发表单验证
image
image

### CODE REVIEW

File: src/Web/MASA.PM.Web.Admin/Pages/Home/Overview.razor.cs [hunk 1]
```diff
@@ -109,6 +110,10 @@ private async Task ShowEnvModalAsync(UpdateEnvironmentDto? model = null)
                 _envFormModel.Show(model);
             }
 
+            if (_envForm is not null)
+            {
+                _envForm.Reset();
```
Comment (MayueCif) [inline src/Web/MASA.PM.Web.Admin/Pages/Home/Overview.razor.cs:115]: _envForm?.Reset();

File: src/Web/MASA.PM.Web.Admin/Pages/Home/Overview.razor.cs [hunk 2]
```diff
@@ -179,6 +184,10 @@ private void EnvModalValueChanged(bool value)
             _envFormModel.Visible = value;
             if (!value)
             {
+                if (_envForm is not null)
+                {
+                    _envForm.Reset();
```
Comment (MayueCif) [inline src/Web/MASA.PM.Web.Admin/Pages/Home/Overview.razor.cs:189]: _envForm?.Reset()

**Review by MayueCif — COMMENTED** [review]
@MapleWithoutWords

**Review by MayueCif — APPROVED** [review]
