### PR TITLE
fix: fix #163 and update masa blazor compontent

### LINKED ISSUE #163: Landscape . Expand and collapse button linkage
不同环境/集群切换后，项目的展开收起会联动

https://user-images.githubusercontent.com/95004531/181402604-9fb75026-fe2f-4361-bc29-6ab1fc2fed9c.mp4

### PR DESCRIPTION
**Pull request by codding-y**

### CODE REVIEW

File: src/Contracts/MASA.PM.Contracts.Admin/Dto/AddAppDto.cs [hunk 1]
```diff
@@ -17,7 +17,7 @@ public string Name
             set => _name = value?.Trim() ?? "";
         }
 
-        [MinCount(1)]
+        [MinCount(1, ErrorMessage = "15s4d5sds")]
```
Comment (doddgu) [inline src/Contracts/MASA.PM.Contracts.Admin/Dto/AddAppDto.cs:20]: ?

**Review by doddgu — DISMISSED** [review]

**Review by MayueCif — APPROVED** [review]
