### PR TITLE
fix: fix #125、#116、#100、#120、#83、#96 bug and update appsettings

### LINKED ISSUE #125: Initialization，The cluster name should be "Default" by Default.
集群名称应默认显示“Default”，可修改
image

### PR DESCRIPTION
**Pull request by codding-y**

### CODE REVIEW

File: src/Services/MASA.PM.Service.Admin/appsettings.Staging.json [hunk 1]
```diff
@@ -4,8 +4,8 @@
     "RedisOptions": {
       "Servers": [
         {
-          "Host": "10.10.90.37",
-          "Port": 30120
+          "Host": "redis-dev-svc.stack",
```
Comment (MayueCif) [inline src/Services/MASA.PM.Service.Admin/appsettings.Staging.json:7]: ?
