### PR TITLE
fix: fix #119、#59、#64 ...

### LINKED ISSUE #119: Team，Click on the application card to enter the edit application
团队详情页，点击应用卡片，应弹出编辑应用弹窗；
image

### PR DESCRIPTION
**Pull request by codding-y**

### CODE REVIEW

File: src/Web/MASA.PM.Web.Admin/Program.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@
 });
 builder.Services.AddMasaStackComponentsForServer("wwwroot/i18n", builder.Configuration["AuthServiceBaseAddress"]);
 
-builder.Services.AddMasaOpenIdConnect(builder.Configuration);
+//builder.Services.AddMasaOpenIdConnect(builder.Configuration);
```
Comment (doddgu) [inline src/Web/MASA.PM.Web.Admin/Program.cs:26]: Why you comment it?

**Review by doddgu — CHANGES_REQUESTED** [review]

**Review by doddgu — APPROVED** [review]
LGTM
